<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Description>Avalonia desktop application for MTranslate.</Description>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../MTranslate.Core/MTranslate.Core.csproj" />
    <ProjectReference Include="../MTranslate.DocumentFormats/MTranslate.DocumentFormats.csproj" />
    <ProjectReference Include="../MTranslate.Infrastructure/MTranslate.Infrastructure.csproj" />
  </ItemGroup>
</Project>
